### ISSUE TITLE
dokuwiki.org: other plugins by the same author are listed without separators

### ISSUE THREAD

**Issue by saggi-dw** [dokuwiki/dokuwiki#4153]
Sample:
https://www.dokuwiki.org/plugin:gchart

`badbehaviouramazonxfortunestatisticstranslationcaptchagraphvizaclinfoditaaand 61 more`

[badbehaviour](https://www.dokuwiki.org/plugin:badbehaviour)[amazon](https://www.dokuwiki.org/plugin:amazon)[xfortune](https://www.dokuwiki.org/plugin:xfortune)[statistics](https://www.dokuwiki.org/plugin:statistics)[translation](https://www.dokuwiki.org/plugin:translation)[captcha](https://www.dokuwiki.org/plugin:captcha)[graphviz](https://www.dokuwiki.org/plugin:graphviz)[acl](https://www.dokuwiki.org/plugin:acl)[info](https://www.dokuwiki.org/plugin:info)[ditaa](https://www.dokuwiki.org/plugin:ditaa)and 61 more

**Comment by fiwswe** [comment]
Looks like a CSS issue in the [Repository Plugin](https://github.com/dokuwiki/dokuwiki-plugin-pluginrepo) (See also [Extension Repository Plugin](https://www.dokuwiki.org/plugin:repository).) So not really a DokuWiki issue.

The extension names are actually separate `<li>` elements so adding CSS to insert some delimiter between each pair should be doable.

Something like this should do the trick:
```css
.dokuwiki div.pluginrepo_entry div.authorInfo ul li+li {
    margin-left: .25em;
}
```

or
```css
.dokuwiki div.pluginrepo_entry div.authorInfo ul li+li:before {
    content: ", ";
}
```
